gcs_paths:
  da_data: "rat-acute-06/epigenomics/da"
  feature_map_data: "rat-acute-06/epigenomics/metadata"

tissue_files:
  liver:
    da_file: "rat-acute-06_t68-liver_epigen-atac-seq_da_timewise-deseq2-phase-frip-t2f-exercise_v1.0.txt"
    feature_map_file: "rat-acute-06_t68-liver_epigen-atac-seq_metadata_features_v1.0.txt"
  # ... add other tissues here ...

analysis_params:
  significance_threshold: 0.05
  clustering:
    k_start: 3
    k_end: 15
    fuzziness: 1.2
    use_precomputed_seeds: false
    num_random_seeds: 5
    explicit_seeds: [19805, 15184, 98839, 23642, 57386, 6259, 55376, 9620, 88540, 57914, 55293, 96857, 7553, 82196, 20470, 96857, 72936, 72936, 26744, 99338, 60150, 55293, 7553, 90714, 60218, 59272]
    explicit_cluster_choice:
      male:
        liver: 9
      female:
        liver: 4
  pathway_enrichment:
    term_size_min: 0
    term_size_max: 400
    top_n_pathways: 75
    
columns:
  p_value_adj: "adj_p_value"
  sex: "sex"
  feature_id: "feature_id"
  timepoint: "timepoint"
  logFC: "logFC"

# For a first run, it's best to search for optimal seeds from scratch.
# The script will save the best seeds it finds for future use.
use_precomputed_seeds: false

# When true, the pipeline will save plots and data CSVs to the local
# output directory specified by `local_base_output_dir`.
export_local_output: true

