# human_cancer_mapping_file: "/Users/curtismcginity/stanford/research/proj/MoTrPAC/dev/data/_feast-human/mapping/pgac_markers.csv"
human_cancer_mapping_file: "/Users/curtismcginity/stanford/research/proj/MoTrPAC/dev/data/_feast-human/mapping/gcd_pdac_2025-10-10.tsv"

human_feature_to_gene_file: "pre-cawg/staging_20250311/human-precovid-sed-adu/latest/resources/motrpac-mappings-human-feature-to-gene.txt"

gcs_paths:
  proteomics:
    da_data: "pre-cawg/staging_20250311/human-precovid-sed-adu/latest/proteomics/da"
    # feature_map_data: "pre-cawg/staging_20250311/human-precovid-sed-adu/latest/proteomics/metadata"
  atac:
    da_data: "pre-cawg/staging_20250311/human-precovid-sed-adu/latest/epigenomics/da"
    # feature_map_data: "pre-cawg/staging_20250311/human-precovid-sed-adu/latest/epigenomics/metadata"
  rna:
    da_data: "pre-cawg/staging_20250311/human-precovid-sed-adu/latest/transcriptomics/da"
    # feature_map_data: "pre-cawg/staging_20250311/human-precovid-sed-adu/latest/transcriptomics/metadata"

blood_files:
  proteomics:
    da_file: "human-precovid-sed-adu_t02-plasma_prot-ol_da_dream-acute_v1.2.txt"
    # feature_map_file: "human-precovid-sed-adu_t02-plasma_prot-ol_metadata_features_v1.2.txt"
  atac:
    da_file: "human-precovid-sed-adu_t05-pbmc_epigen-atac-seq_da_dream-acute_v1.2.txt"
    # feature_map_file: "human-precovid-sed-adu_t05-pbmc_epigen-atac-seq_metadata_features_v1.2.txt"
  rna:
    da_file: "human-precovid-sed-adu_t04-blood-rna_transcript-rna-seq_da_dream-acute_v1.2.txt"
    # feature_map_file: "human-precovid-sed-adu_t04-blood-rna_transcript-rna-seq_metadata_features_v1.2.txt"
  # ... add other blood files here ...

analysis_params:
  significance_threshold: 0.05
  pathway_enrichment:
    term_size_min: 0
    term_size_max: 4000
    top_n_pathways: 7500
    
columns:
  p_value_adj: "adj_p_value"
  # sex: "sex"
  feature_id: "feature_id"
  # timepoint: "timepoint"
  logFC: "logFC"



